### ISSUE TITLE
 Failed to init broadcaster: application context is probably not web application context

### ISSUE THREAD

**Issue by shadeimi** [seleniumkit/selenograph#3]
=============== Full stacktrace follows: ===============
Caused by java.lang.RuntimeException: Failed to init broadcaster: application context is probably not web application context!: Failed to init broadcaster: application context is probably not web application context!
    at ru.yandex.qatools.camelot.web.core.AtmosphereClientBroadcastersProvider.initBroadcaster(AtmosphereClientBroadcastersProvider.java:70)
    at ru.yandex.qatools.camelot.web.core.AtmosphereClientBroadcastersProvider.getBroadcaster(AtmosphereClientBroadcastersProvider.java:50)
    at ru.yandex.qatools.camelot.web.core.LocalPluginFrontendNotifier$Notifier.notify(LocalPluginFrontendNotifier.java:39)
    at sun.reflect.GeneratedMethodAccessor88.invoke(null)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at ru.yandex.qatools.camelot.common.AnnotatedMethodDispatcher.callMethod(AnnotatedMethodDispatcher.java:107)
    at ru.yandex.qatools.camelot.common.AnnotatedMethodDispatcher.findSuitableMethodAndCall(AnnotatedMethodDispatcher.java:95)
    at ru.yandex.qatools.camelot.common.AnnotatedMethodDispatcher.call(AnnotatedMethodDispatcher.java:66)
    at ru.yandex.qatools.camelot.common.AnnotatedMethodDispatcher.dispatch(AnnotatedMethodDispatcher.java:42)
    at ru.yandex.qatools.camelot.common.PluggableProcessor.dispatchMessage(PluggableProcessor.java:75)
    at ru.yandex.qatools.camelot.common.PluggableProcessor.process(PluggableProcessor.java:61)
    at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
    at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
    at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
    at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
    at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)
    at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:141)
    at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
    at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
    at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
    at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
    at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
    at org.apache.camel.processor.UnitOfWorkProducer.process(UnitOfWorkProducer.java:68)
    at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:412)
    at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:380)
    at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:270)
    at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:380)
    at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:221)
    at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:124)
    at org.apache.camel.impl.DefaultProducerTemplate.sendBodyAndHeaders(DefaultProducerTemplate.java:233)
    at org.apache.camel.impl.DefaultProducerTemplate.sendBodyAndHeaders(DefaultProducerTemplate.java:379)
    at ru.yandex.qatools.camelot.util.ServiceUtil$3.produce(ServiceUtil.java:184)
    at ru.yandex.qatools.camelot.mongodb.MongodbClientSendersProvider.lambda$null$10(MongodbClientSendersProvider.java:101)
    at ru.qatools.mongodb.MongoTailableQueue.lambda$poll$4(MongoTailableQueue.java:82)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at ru.qatools.mongodb.MongoTailableQueue.poll(MongoTailableQueue.java:82)
    at ru.yandex.qatools.camelot.mongodb.MongodbClientSendersProvider.lambda$initPoller$11(MongodbClientSendersProvider.java:101)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by smecsia** [comment]
@shadeimi Thanks for the report! Please describe the steps how you launch the server.

**Comment by Shnitzelil** [comment]
I've encounter this also

**Comment by shaburov** [comment]
+1
Caused by java.lang.RuntimeException: Failed to init broadcaster: application context is probably not web application context!: Failed to init broadcaster: application context is probably not web application context!
+
![image](https://user-images.githubusercontent.com/15269131/30595021-a4ca5912-9d58-11e7-828f-251f9a73c7cd.png)
+
![image](https://user-images.githubusercontent.com/15269131/30595043-b2a47cac-9d58-11e7-9658-b595ed9e98dc.png)
+
[grid-router.log](https://github.com/shaburov/buginfo/blob/master/seleniumkit/selenograph/issues/3/grid-router.log)

**Comment by vania-pooh** [comment]
@shaburov JFYI this project is abandoned. Currently supported Selenium load balancer implementation is: http://github.com/aerokube/ggr. This is what we are using in production. It is using the same XML quota files and encrypted `htpasswd` for users.
