### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by mistic** [seleniumkit/selenograph#4]
Hi guys,

I'm trying to install that on Ubuntu 14.04 but i'm having some problems.
I've installed mongodb before and after that i've done your install steps. The process starts but i can't see the app running. 

I'm trying to access the app on:

http:/ip:4444/wd/hub but i'm getting:

HTTP ERROR: 503
Problem accessing /wd/hub. Reason:
    Service Unavailable
Powered by Jetty:// 9.3.3.v20150827

Any ideas here?

Regards

**Comment by vania-pooh** [comment]
@misticini how about looking in log files: `$ tail -100 /var/log/selenograph/selenograph.log`?

**Comment by ngtandat** [comment]
I got the same issue and here is the log. Attached is the log and configuration files.
[grid-router.zip](https://github.com/seleniumkit/selenograph/files/389605/grid-router.zip)

```
2016-07-28 23:11:22,964 [main                          ] INFO  ePropertyPlaceholderConfigurer - Loading properties file from URL [file:/etc/grid-router/selenograph.prop
erties]
2016-07-28 23:11:22,968 [main                          ] WARN  XmlWebApplicationContext       - Exception encountered during context initialization - cancelling refresh
 attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'configRepository' defined in URL [jar:file:/tmp/jetty-0.0.0
.0-4444-selenograph-deb.war-_-any-8073106799459005861.dir/webapp/WEB-INF/lib/selenograph-service-1.1.jar!/camelot-extensions.xml]: Could not resolve placeholder 'grid.r
outer.quota.repository' in string value "${grid.router.quota.repository}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'grid.r
outer.quota.repository' in string value "${grid.router.quota.repository}"
2016-07-28 23:11:22,971 [main                          ] ERROR ContextLoader                  - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'configRepository' defined in URL [jar:file:/tmp/jetty-0.0.0.0-4444-se
lenograph-deb.war-_-any-8073106799459005861.dir/webapp/WEB-INF/lib/selenograph-service-1.1.jar!/camelot-extensions.xml]: Could not resolve placeholder 'grid.router.quot
a.repository' in string value "${grid.router.quota.repository}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'grid.router.quot
a.repository' in string value "${grid.router.quota.repository}"
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:211)[spring-beans-4.2.3.RELEASE.j
ar:4.2.3.RELEASE]
        at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:222)[spring-beans-4.2.3.RELEASE.j
ar:4.2.3.RELEASE]
        at ru.yandex.qatools.camelot.spring.ListablePropertyPlaceholderConfigurer.processProperties(ListablePropertyPlaceholderConfigurer.java:54)[camelot-core-2.5.4.ja
r:]
        at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:86)[spring-beans-4.2.3.RELEASE.jar
:4.2.3.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)[spring-cont
ext-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166)[spring-cont
ext-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:677)[spring-context-4.2.3.RELE
ASE.jar:4.2.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:835)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:530)[jetty-servlet-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:808)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:342)[jetty-servlet-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1368)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1335)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)[jetty-servlet-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:511)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.server.Server.start(Server.java:405)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)[jetty-server-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[jetty-util-9.3.6.v20151106.jar:9.3.3.v20150827]
        at org.eclipse.jetty.runner.Runner.run(Runner.java:502)
        at org.eclipse.jetty.runner.Runner.main(Runner.java:547)
=============== Full stacktrace follows: ===============
Caused by org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'configRepository' defined in URL [jar:file:/tmp/jetty-0.0.0
.0-4444-selenograph-deb.war-_-any-8073106799459005861.dir/webapp/WEB-INF/lib/selenograph-service-1.1.jar!/camelot-extensions.xml]: Could not resolve placeholder 'grid.r
outer.quota.repository' in string value "${grid.router.quota.repository}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'grid.r
outer.quota.repository' in string value "${grid.router.quota.repository}": Invalid bean definition with name 'configRepository' defined in URL [jar:file:/tmp/jetty-0.0.
0.0-4444-selenograph-deb.war-_-any-8073106799459005861.dir/webapp/WEB-INF/lib/selenograph-service-1.1.jar!/camelot-extensions.xml]: Could not resolve placeholder 'grid.
router.quota.repository' in string value "${grid.router.quota.repository}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'grid.
router.quota.repository' in string value "${grid.router.quota.repository}"
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:211)
        at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:222)
        at ru.yandex.qatools.camelot.spring.ListablePropertyPlaceholderConfigurer.processProperties(ListablePropertyPlaceholderConfigurer.java:54)
        at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:86)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:677)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:835)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:530)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:808)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:342)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1368)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1335)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:511)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:405)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.runner.Runner.run(Runner.java:502)
        at org.eclipse.jetty.runner.Runner.main(Runner.java:547)
Caused by java.lang.IllegalArgumentException: Could not resolve placeholder 'grid.router.quota.repository' in string value "${grid.router.quota.repository}": Could not
resolve placeholder 'grid.router.quota.repository' in string value "${grid.router.quota.repository}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
        at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer$PlaceholderResolvingStringValueResolver.resolveStringValue(PropertyPlaceholderConfigur
er.java:258)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanClassName(BeanDefinitionVisitor.java:101)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:78)
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:208)
        at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:222)
        at ru.yandex.qatools.camelot.spring.ListablePropertyPlaceholderConfigurer.processProperties(ListablePropertyPlaceholderConfigurer.java:54)
        at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:86)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:677)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:835)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:530)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:808)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:342)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1368)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1335)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:511)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:405)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.runner.Runner.run(Runner.java:502)
        at org.eclipse.jetty.runner.Runner.main(Runner.java:547)
```

**Comment by smecsia** [comment]
@ngtandat Please use the workaround described in #7 

``` xml
grid.router.quota.repository=ru.qatools.gridrouter.ConfigRepositoryXml
```

**Comment by ngtandat** [comment]
Hi Ilya, 

Thanks for quick response but I am still getting this error after applying this workaround:
Here is the steps:
1. Install Selenograph by following the instruction at https://github.com/seleniumkit/selenograph 
2. Adding "grid.router.quota.repository=ru.qatools.gridrouter.ConfigRepositoryXml" to /etc/grid-router/application.properties
3. Restart the service: service yandex-selenograph restart
4. Access http:/ip:4444/

I also checked the log and still getting the same error.

Thanks again.
Dat

**Comment by smecsia** [comment]
@ngtandat Please try to add the same line not to `/etc/grid-router/application.properties`, but to `/etc/grid-router/selenograph.properties`

**Comment by ngtandat** [comment]
Thanks a lot. It works now. I can access the Selenograph web.

**Comment by ngtandat** [comment]
Nothing shown on the web except the Selenograph header. I also tried to start one hub and add it to test.xml.

Below is error in log:

```
=============== Full stacktrace follows: ===============
Caused by com.mongodb.MongoCommandException: Command failed with error 15981: 'exception: the $unwind field path must be specified as a string' on server localhost:27017. The full response is { "errmsg" : "exception: the $unwind field path must be specified as a string", "code" : 15981, "ok" : 0.0 }: Command failed with error 15981: 'exception: the $unwind field path must be specified as a string' on server localhost:27017. The full response is { "errmsg" : "exception: the $unwind field path must be specified as a string", "code" : 15981, "ok" : 0.0 }
    at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:86)
    at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:120)
    at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
    at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
    at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
    at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
    at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
    at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:112)
    at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:227)
    at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:223)
    at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239)
    at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
    at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:223)
    at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:65)
    at com.mongodb.Mongo.execute(Mongo.java:772)
    at com.mongodb.Mongo$2.execute(Mongo.java:759)
    at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
    at com.mongodb.AggregateIterableImpl.iterator(AggregateIterableImpl.java:102)
    at com.mongodb.AggregateIterableImpl.iterator(AggregateIterableImpl.java:40)
    at java.lang.Iterable.forEach(Iterable.java:74)
    at ru.qatools.selenograph.ext.SelenographDB.sessionsByUserCount(SelenographDB.java:163)
    at ru.qatools.selenograph.ext.SelenographDB.getQuotasSummary(SelenographDB.java:119)
    at ru.qatools.selenograph.gridrouter.QuotaSummaryClientNotifier.sendUpdatesToClient(QuotaSummaryClientNotifier.java:29)
    at sun.reflect.GeneratedMethodAccessor58.invoke(null)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at ru.yandex.qatools.camelot.common.PluginAnnotatedMethodInvoker.invoke(PluginAnnotatedMethodInvoker.java:71)
    at ru.yandex.qatools.camelot.common.builders.QuartzAggregatorSchedulerBuilder.invokeJob(QuartzAggregatorSchedulerBuilder.java:175)
    at ru.yandex.qatools.camelot.common.builders.QuartzAggregatorSchedulerBuilder$ScheduledJob.execute(QuartzAggregatorSchedulerBuilder.java:216)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
2016-08-01 22:18:10,225 [Timer-1                       ] INFO  SessionsAggregator             - Flushing upsert buffer. Queue size is 0
root@ubuntu:/var/log/grid-router# 
```

Please help to take a look. Thanks again, Dat.

**Comment by smecsia** [comment]
@ngtandat which version of MongoDB are you using?

**Comment by ngtandat** [comment]
@smecsia I am using MongoDB 3.0.12.

**Comment by smecsia** [comment]
@ngtandat Could you try MongoDB > 3.2 ?

**Comment by ngtandat** [comment]
@smecsia Thanks. It works with MongoDB 3.2.8.
